# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CSCI535_hw7',
                'doc_host': 'https://gmenderson.github.io',
                'git_url': 'https://github.com/gmenderson/CSCI535_hw7',
                'lib_path': 'CSCI535_hw7'},
  'syms': {'CSCI535_hw7.core': {'CSCI535_hw7.core.foo': ('core.html#foo', 'CSCI535_hw7/core.py')}}}
